PR #2
virtual-labs/exp-critical-micelle-concentration-iiith pull request #4
Opened 2021-04-29 07:55 UTC by umangS77

Issues reported on 27/04/21 resolved

2021-05-02 09:09 UTC, raj-vlabs requested changes
The issues raised during the meet seem to have been addressed. However, I was just looking at the experiment and noticed the following:
1. For some instructions it is not clear as to which jar/beaker has to be clicked.
2. The mouse pointer doesn't change on the clickable elements. So it is difficult to know which element is clickable and which is not.
3. The click works for all the elements and not only for those required for the next steps. As a result someone can accidentally click a different element and erroneously complete the experiment.
I think the above points need a little bit of attention in the interest of usability.

2021-05-02 09:09 UTC, raj-vlabs commented on experiment/simulation/css/main.css
> +.instructionsBox{
Please rename this to use a hyphenated name according to the css variable naming convention

2021-05-03 13:04 UTC, umangS77 commented on experiment/simulation/css/main.css
> +.instructionsBox{
Thanks for pointing these issues sir. I'll fix them asap.

2021-08-06 07:18 UTC, raj-vlabs approved these changes
Please remove the http link in references before merging.

2021-08-06 07:18 UTC, raj-vlabs commented on .github/workflows/deployment-script.yml
> +        git clone https://github.com/virtual-labs/ph3-lab-mgmt
Add --depth=1

2021-08-06 07:18 UTC, raj-vlabs commented on experiment/references.md
> +4. [http://nsdl.niscair.res.in/bitstream/123456789/311/1/PDF+corrected+surface+chemistry.pdf](http://nsdl.niscair.res.in/bitstream/123456789/311/1/PDF+corrected+surface+chemistry.pdf)
Change the link to https and provide a meaningful text in place of giving the whole link

2021-08-06 07:49 UTC, merged